apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/egangithub1502/gitops-nginx
    targetRevision: master
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
